var config = require('../config')
const utils = require('../utils')

describe('HPID Social Sign In', function () {
    xit('should log in via Google', function () {
        browser.url(utils.getLoginUI())
        browser.waitForExist('#Google-Button')
        browser.click('#Google-Button')
        browser.waitForExist('#identifierId')
        browser.setValue('#identifierId', config.socialUser)
        browser.click('#identifierNext')
        browser.waitForVisible('#password')
        browser.click('#password')
        browser.setValue('input[type="password"]', config.socialPassword)
        browser.click('#passwordNext')
        browser.waitForExist('.headerPart h4')
        expect(browser.getText('.headerPart h4')).toBe(config.accountHeader)
        browser.click('.vn-icon')
        browser.click('.signOut_clickable')
    })

    xit('should log in via OneHP', function () {
        browser.url(utils.getLoginUI())
        browser.waitForExist('div.social-login-buttons > a:nth-child(3)')
        browser.click('div.social-login-buttons > a:nth-child(3)')
        browser.waitForExist('#Login')
        browser.setValue('#username', config.socialHPUser)
        browser.setValue('#password', config.socialHPPassword)
        browser.click('input[type="submit"]')
        browser.waitForExist('.headerPart h4')
        expect(browser.getText('.headerPart h4')).toBe(config.accountHeader)
        browser.click('.vn-icon')
        browser.click('.signOut_clickable')
    })

    it('should log in via Facebook', function () {
        browser.url(utils.getLoginUI())
        browser.waitForExist('#g10')
        browser.click('#g10')
        browser.waitForExist('#email')
        browser.setValue('#email', config.socialFBUser)
        browser.setValue('#pass', config.socialFBPassword)
        browser.click('#loginbutton') // CAN'T PASS -> FB DENIES REDIRECT
        browser.waitForExist('.headerPart h4')
        expect(browser.getText('.headerPart h4')).toBe(config.accountHeader)
        browser.click('.vn-icon')
        browser.click('.signOut_clickable')
    })
})